version: "3.4"

services:
  tripplanner-api:
    depends_on:
      - sql
    image: ${DOCKER_REGISTRY-}tripplannerapi
    build:
      context: .
      dockerfile: ./TripPlanner.API/Dockerfile
    ports:
      - "5000:80"
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=myStong_Password123#
