name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  back-end:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Deploy Backend
        run: |
          cd Back-end
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml up -d

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install Okteto CLI
        run: |
          curl https://get.okteto.com -sSfL | sh
          sudo mv /usr/local/bin/okteto /usr/local/bin/okteto

      - name: Authenticate with Okteto
        run: okteto login --token jFjquV8P0AbTToon1ompj19hpYoU1ZPBOKbT5JHB4Sf7OjKv

      - name: Deploy to Okteto
        run: okteto stack deploy
