name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  back-end:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Deploy Backend
        run: |
          cd ./Back-end
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml up -d

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      # this okteto cloud works without error
      - name: Set context to Okteto Cloud
        uses: okteto/context@latest
        with:
          token: jFjquV8P0AbTToon1ompj19hpYoU1ZPBOKbT5JHB4Sf7OjKv
        
      # HERE I GET AN ERROR
      #running: okteto build --progress plain -f ./Back-end/docker-compose.yml
      # i  Using eliasgrinwis @ cloud.okteto.com as context
      # !  Build 'tripplanner-api': Dockerfile 'TripPlanner.API/Dockerfile' is not in a relative path to context 'Back-end'
      # x  Error building service 'tripplanner-api': invalid build context: 'Back-end' does not exist

      - name: Build and Deploy to Okteto Cloud
        uses: okteto/build@latest
        with:
          tag: myapp-backend:latest
          file: ./Back-end/docker-compose.yml
          path: ./Back-end
