name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  back-end:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Deploy Backend
        run: |
          cd ../Back-end
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml up -d

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Set context to Okteto Cloud
        uses: okteto/context@v2
        with:
          token: jFjquV8P0AbTToon1ompj19hpYoU1ZPBOKbT5JHB4Sf7OjKv

      - name: Build and Deploy to Okteto Cloud
        uses: okteto/build@latest
        with:
          file: ../Back-end/docker-compose.yml
