name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  back-end:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Deploy Backend
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml up -d

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"
      
      - name: Install Okteto CLI
        run: |
          curl https://get.okteto.com -sSfL | sh

      - name: Set context to Okteto Cloud
        uses: okteto/context@latest
        with:
          token: jFjquV8P0AbTToon1ompj19hpYoU1ZPBOKbT5JHB4Sf7OjKv
      
      - name: Build to Okteto Cloud
        uses: okteto/build@latest 
        with: 
          tag: myapp-backend:latest 
          file: ./docker-compose.yml 
      
      - name: Deploy to Okteto Cloud
        run: |
          okteto context use https://cloud.okteto.com
          okteto deploy
        env:
          OKTETO_TOKEN: jFjquV8P0AbTToon1ompj19hpYoU1ZPBOKbT5JHB4Sf7OjKv