name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  back-end:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Deploy Backend
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml up -d

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"
      
      - name: Install Okteto CLI
        run: |
          curl https://get.okteto.com -sSfL | sh

      - name: Set context to Okteto Cloud
        uses: okteto/context@latest
        with:
          token: jFjquV8P0AbTToon1ompj19hpYoU1ZPBOKbT5JHB4Sf7OjKv
      
      - name: Build to Okteto Cloud
        uses: okteto/build@latest 
        with: 
          tag: myapp-backend:latest 
          file: ./docker-compose.yml 
      
      - name: Deploy to Okteto Cloud
        run: |
          okteto context use https://cloud.okteto.com
          okteto deploy
        env:
          OKTETO_TOKEN: jFjquV8P0AbTToon1ompj19hpYoU1ZPBOKbT5JHB4Sf7OjKv
  
  front-end:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "14"
      - run: |
          pwd
          cd ./Front-end
          npm install
          npm run build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: 1//096Mn1E67cFirCgYIARAAGAkSNwF-L9IrlD2avG8X5NGaeLFbnC2dGJdWzAWyHCvb3KDxuiLf7c3h0LL3Y1AcC2UBAY8sOlwM-50